default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: acquainted_dev

test:
  <<: *default
  database: acquainted_test

production:
  <<: *default
  database: acquainted_prod
